# Node.js backend Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
ARG BUILD_ENV=development
RUN if [ "$BUILD_ENV" = "production" ]; then npm install --production; else npm install; fi
COPY . .
EXPOSE 4000
CMD ["npm", "start"]
