version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=admin@tuodominio.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    restart: unless-stopped

  omega_app:
    build: .
    container_name: omega_app
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omega.rule=Host(`tuodominio.com`)"
      - "traefik.http.routers.omega.entrypoints=websecure"
      - "traefik.http.routers.omega.tls.certresolver=le"
    expose:
      - "3000"
    restart: unless-stopped

volumes:
  letsencrypt:
    driver: local
