name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend deps
        run: |
          cd omega-app/backend
          npm ci
      - name: Lint / test (skipped placeholder)
        run: echo "Add lint/test steps"
      - name: Build frontend
        run: |
          cd omega-app/frontend
          npm ci
          npm run build
